name: Terraform Apply

on:
  push:
    branches:
      - main
  workflow_run:
    workflows: ["Terraform Plan"]
    branches:
      - main
    types:
      - completed

jobs:
  terraform_apply:
    if: github.ref == 'refs/heads/main'
    environment:
      name: prod
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.7"
      - name: Terraform Init
        run: terraform init
      - name: Zip the code
        working-directory: lambda
        run: sh make_zip.sh
      - name: Terraform Apply
        env:
          TF_VAR_aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          TF_VAR_aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_aws_region: ${{ vars.AWS_REGION }}
          TF_VAR_lambda_role_arn: ${{ secrets.LAMBDA_ROLE_ARN }}
          TF_VAR_scheduler_role_arn: ${{ secrets.SCHEDULER_ROLE_ARN }}
          TF_VAR_discord_webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          terraform apply --auto-approve
